version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    expose:
      - "80"
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/www:/var/www
    networks:
      - proxy
networks:
  proxy:
    driver: bridge
